version: "3.8"

services:
  db:
    image: postgres:16.2
    environment:
      - POSTGRES_DB=core
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=P4ssword!
    ports:
      - 5433:5432

    volumes:
      - core-data:/var/lib/postgresql/data

  core:
    image: pholluxion/core:latest
    environment:
    - POSTGRES_HOST=db
    - POSTGRES_PORT=5432
    - POSTGRES_DATABASE=core
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=P4ssword!
    - PORT=8080

    ports:
    - 8080:8080

    depends_on:
    - db

    volumes:
    - core-data:/app/data

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - rabbitmq-network

    volumes:
      - rabbitmq-data:/var/lib/rabbitmq

networks:
    rabbitmq-network:
        driver: bridge

volumes:
    rabbitmq-data:
    core-data:
